# Generated by Django 5.1.1 on 2024-10-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_comment_username_bid_listing_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(max_length=30000, null=True),
        ),
    ]
